title: Jared Chung Data Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: jaredchung.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: jaredchung
   linkedin: jaredchung
   email: jared_chung@hotmail.com

google_analytics: "UA-58263416-1"
